version: '3.9'

services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${AJ_NEXTCLOUD_DATA_DIR}/postgres_data:/var/lib/postgresql/data
    networks:
      - ajnet

  redis:
    image: redis:latest
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${AJ_NEXTCLOUD_DATA_DIR}/redis_data:/data
    networks:
      - ajnet

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ${AJ_NEXTCLOUD_DATA_DIR}/pgadmin_data:/var/lib/pgadmin
      - ${AJ_NEXTCLOUD_DATA_DIR}/servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - ajnet

  nextcloud:
    image: nextcloud:30
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      POSTGRES_HOST: postgres:5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: redis
      REDIS_HOST_PORT: 6379
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ${AJ_NEXTCLOUD_DATA_DIR}/nextcloud_data:/var/www/html
    ports:
      - "${NEXTCLOUD_PORT}:80"
    networks:
      - ajnet

networks:
  ajnet:
